server:
  port: 8080

grpc:
  server:
    port: 9090
  client:
    inventory:
      address: static://localhost:9091
      negotiationType: plaintext

spring:
  application:
    name: placeorder-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: placeorder-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

inventory:
  http:
    base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
